(*.F- *)
(**********************************************************************
|  Title   : DGH.INI reader
|  Author  : MPostol
|  System  : LOGITECH MODULA-2/86
|  History :
|    Rel 3.16: MPostol
|      Aby zaoszczedzic pamiec zostala zdefiniowana imp pusta dla arch
|
|  Copyright (C), CAS LODZ POLAND.
|  TEL: 42' 686 25 47
|  mailto: techsupp@cas.com.pl
|  http: www.cas.com.pl
|
**********************************************************************)
(*.F+ *)
IMPLEMENTATION MODULE DGHIni;

END DGHIni.
