m2c CommonTy/NOA/B CommonDa/NOA/B MANAGER/NOA/B SoftIntH/NOA/B DOSEntry/NOA/B GrafType/NOA/B StdIO/NOA/B
m2c XMSServi/NOA/B FIO/NOA/B Graphics/NOA/B Timer/NOA/B HRD_Cloc/NOA/B ShortCut/NOA/B Semafory/NOA/B MMMouse/NOA/B
m2c Czas/NOA/B SpecConv/NOA/B WorseBec/NOA/B FlagAnal/NOA/B MMA_Cout/NOA/B FCBS/NOA/B HiLevGra/NOA/B GrafUtil/NOA/B
m2c Messages/NOA/B Ini/NOA/B DGHIni/NOA/B DigiRS/NOA/B GPS_TRIM/NOA/B FIltr1St/NOA/B Math/NOA/B Theodoli/NOA/B
m2c GPS_nov/NOA/B GPSRead/NOA/B AltInter/NOA/B DGHInter/NOA/B Kl_FGene/NOA/B Kalibrac/NOA/B ARINC/NOA/B
m2c NAVInter/NOA/B DGH_util/NOA/B GeoArith/NOA/B Int_DME/NOA/B PI_PA/NOA/B Files/NOA/B Buttons/NOA/B GList/NOA/B
m2c InpLine/NOA/B Dialog/NOA/B MsgBox/NOA/B DrawEpso/NOA/B Marks/NOA/B Polozeni/NOA/B DataColl/NOA/B EventsMn/NOA/B
m2c Mapa/NOA/B Obloty/NOA/B SwitchCn/NOA/B Tune/NOA/B Print/NOA/B PrintUtl/NOA/B ErrorMes/NOA/B DisResUt/NOA/B
m2c PiszEven/NOA/B PrintCnt/NOA/B ScreenCT/NOA/B Slupek/NOA/B XMSTable/NOA/B Wykres/NOA/B Screen/NOA/B Pomiar/NOA/B
m2c SimScann/NOA/B CocpDsp/NOA/B PrintScr/NOA/B R:av/NOA/B
m2l R:av
