(*.F- *)
(**********************************************************************
|  Title   : GS Common types 
|  Author  : M.Postol
|  System  : LOGITECH MODULA-2/86 
|  History :
|
|  Copyright (C), CAS LODZ POLAND.
|  TEL: 42' 862 547, 42' 87 80 44 FAX/TEL: 42' 84 48 40
|
**********************************************************************)
(*.F+ *)
IMPLEMENTATION MODULE G_CommonTypes;

END G_CommonTypes.
